### PR TITLE
When Prospector is installed, only generate patches when last ore is depleted

### PR DESCRIPTION
**Pull request by DarkShadow44**
Just a small QoL improvement for usage with the Prospector mod.

Not quite sure why you used "string.find" instead of equality comparison though. If there was a specific reason for that, please tell me, so I can make sure I didn't break anything.

### CODE REVIEW

**Comment by VortiK** [comment]
Hello, 

Thanks for your contribution ! I don't know the Prospector mod, why does it make sense to only generate patches when prospecting is done ?

As for the string comparison, I can't remember now, but I may have had issues with plain == in some cases.

**Comment by DarkShadow44** [comment]
Basically, the Prospector mod turns all ore entities into "depleted ore", which then can be turned into normal ore again. You can do that two times, then the ore really disappears. I feel like the deep core mining patches should only appear when the ore is really gone, to me it doesn't make sense to already get them when there's still plenty of ore left.

**Comment by DarkShadow44** [comment]
Any news on this?

**Comment by VortiK** [comment]
Hello this has been integrated in version 2.3.0. Sorry it took so long and thanks for your contribution !

**Pull request closed without merging**
